[package]
name = "wincraft"
version = "0.6.1"
edition = "2021"
description = "Modular Windows 11 tray utility"
authors = ["WinCraft contributors"]

[dependencies]
log = { version = "=0.4.34", features = ["std"] }
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = "=1.0.151"
eframe = { version = "=0.36.1", default-features = false, features = ["default_fonts", "glow"] }
egui = "=0.36.1"
egui_commonmark = "=0.25.0"
ureq = "=3.4.0"
winit = "=0.30.13"
raw-window-handle = "=0.6.2"

[dependencies.windows-sys]
version = "=0.61.2"
features = [
    "Win32_Foundation",
    "Win32_Globalization",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Shell",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_Graphics_Gdi",
    "Win32_System_Registry",
    "Win32_System_Threading",
    "Win32_System_LibraryLoader",
    "Win32_UI_HiDpi",
    "Win32_System_SystemInformation",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_UI_Controls",
    "Win32_System_DataExchange",
    "Win32_System_Memory",
    "Win32_System_Ole",
    "Win32_Graphics_Dwm",
    "Win32_System_Time",
    "Win32_UI_Controls_Dialogs",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_Variant",
    "Win32_UI_Shell_PropertiesSystem",
]

[build-dependencies]
winresource = "=0.1.31"

[profile.release]
opt-level = "z"
lto = true
strip = true
